### ISSUE TITLE
Module not found: Can't resolve 'react-hot-toast'

### ISSUE THREAD

**Issue by nrzAmirHo3in** [Kuzma02/Electronics-eCommerce-Shop-With-Admin-Dashboard-NextJS-NodeJS#13]
I see this error after `npm run dev`:
![image](https://github.com/user-attachments/assets/b7d90e3a-f3d2-4c41-a308-8a4277fa7cc2)

I tested these methods:

`npm install react-hot-toast`
`npm cache clean --force`
`npm install`

But still error is here!

**Comment by Kuzma02** [comment]
Hi! You can try the following: In your terminal, go to your project folder and run "rm—rf node_modules." After that, run "npm install." You can try running your project now. I hope it solves the problem.

**Comment by nrzAmirHo3in** [comment]
Thanks for your feedback
it works after removing node_modules and reinstall again.

**Comment by nrzAmirHo3in** [comment]
Thanks for your feedback
it works after removing node_modules and reinstall again.
