### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by sandeepdotnetdeveloper** [Kuzma02/Electronics-eCommerce-Shop-With-Admin-Dashboard-NextJS-NodeJS#14]
.next/types/app/api/auth/[...nextauth]/route.ts:8:13
Type error: Type 'OmitWithTag<typeof import("F:/DemoProject/EcommerceApp/app/api/auth/[...nextauth]/route"), "DELETE" | "POST" | "PUT" | "config" | "generateStaticParams" | "revalidate" | "dynamic" | "dynamicParams" | ... 7 more ... | "PATCH", "">' does not satisfy the constraint '{ [x: string]: never; }'.
  Property 'handler' is incompatible with index signature.
    Type 'any' is not assignable to type 'never'.

   6 |
   7 | // Check that the entry is a valid entry
>  8 | checkFields<Diff<{
     |             ^
   9 |   GET?: Function
  10 |   HEAD?: Function
  11 |   OPTIONS?: Function
   Linting and checking validity of types

**Comment by Kuzma02** [comment]
Hi! I'm sorry, but I didn't try to build this project. There might be errors in the building process that you need to solve. In your case, you've encountered a TypeScript type error. It suggests that the types in your API route are not correctly aligned with what Next.js expects. If you find a solution please post it here.

**Comment by sandeepdotnetdeveloper** [comment]
**Updated route.ts** 

import NextAuth, { NextAuthOptions } from "next-auth";
import { Account, User as AuthUser } from "next-auth";
import GithubProvider from "next-auth/providers/github";
import CredentialsProvider from "next-auth/providers/credentials";
import GoogleProvider from "next-auth/providers/google";
import bcrypt from "bcryptjs";
import prisma from "@/utils/db";
import { nanoid } from "nanoid";

const authOptions: NextAuthOptions = {
  providers: [
    CredentialsProvider({
      id: "credentials",
      name: "Credentials",
      credentials: {
        email: { label: "Email", type: "text" },
        password: { label: "Password", type: "password" },
      },
      async authorize(credentials: Record<string, string> | undefined): Promise<AuthUser | null> {
        if (!credentials?.email || !credentials?.password) {
          return null; // Return null if credentials are missing
        }

        try {
          const user = await prisma.user.findFirst({
            where: {
              email: credentials.email,
            },
          });

          if (user && user.password) {
            const isPasswordCorrect = await bcrypt.compare(credentials.password, user.password);

            if (isPasswordCorrect) {
              return user; // Return the user if password is correct
            }
          }

          return null; // Return null if the user is not found or password is incorrect
        } catch (err) {
          console.error("Error during authorization:", err);
          return null; // Ensure we return null on error
        }
      },
    })
  ],
  callbacks: {
    async signIn({ user, account }: { user: AuthUser; account: Account | null }): Promise<boolean> {
      // Check if account is null
      if (account === null) {
        console.log("Account is null.");
        return false; // Return false if account is null (sign-in fails)
      }

      // Check for 'credentials' provider
      if (account.provider === "credentials") {
        return true; // Return true if the provider is 'credentials'
      }

      // Handle OAuth providers (GitHub, Google)
      if (account.provider === "github" || account.provider === "google") {
        try {
          const existingUser = await prisma.user.findFirst({ where: { email: user.email! } });

          if (!existingUser) {
            await prisma.user.create({
              data: {
                id: nanoid(),
                email: user.email!,
              },
            });
          }

          return true; // Return true if the user sign-in was successful
        } catch (err) {
          console.error("Error saving user", err);
          return false; // Return false if there was an error
        }
      }

      return true; // Return true by default if no specific provider is matched
    }
  }
};

const handler = NextAuth(authOptions);
export { handler as GET, handler as POST };
